### Login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "user@example.com",
  "password": "Password@123"
}

### Refresh token
POST {{baseUrl}}/auth/refresh
Content-Type: {{contentType}}

{
  "token": "{{refreshToken}}"
}

### Logout
POST {{baseUrl}}/auth/logout
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}
