### Criar usuário
POST {{baseUrl}}/user/
Content-Type: {{contentType}}

{
  "username": "bruno123",
  "email": "user@mail.com",
  "password": "Password@123"
}

### Buscar usuário por ID (requer JWT)
GET {{baseUrl}}/user/{{userId}}
Authorization: Bearer {{accessToken}}

### Buscar todos os usuários (requer JWT)
GET {{baseUrl}}/user/
Authorization: Bearer {{accessToken}}